Test

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -74,93 +74,93 @@ jobs:
         with:
           name: docker-image
           path: ${{ steps.build.outputs.output_dir }}
-  peeps-tests:
-    name: Run PEEPS tests
-    needs:
-      - docker-build
-    runs-on: ubuntu-20.04
-    steps:
-      - name: 'Checkout'
-        uses: actions/checkout@v2
-      - name: 'Download workflow artifact - Docker image'
-        uses: actions/download-artifact@v1
-        with:
-          name: docker-image
-      - name: 'Load Docker image'
-        id: setup
-        run: |
-          tar xfvz docker-image/quorum-pr.tar.gz
-          docker load --input quorum-pr.tar
-          docker image tag quorumengineering/quorum:pr quorumengineering/quorum:develop
-          docker image ls
-      - name: Set up Java
-        uses: actions/setup-java@v2
-        with:
-          distribution: 'adopt'
-          java-version: 11
-          check-latest: true
-      - name: PEEPS
-        run: | 
-          cd build
-          ./run-peeps.sh
-      - name: PEEPS Test Report
-        uses: mikepenz/action-junit-report@v2
-        if: always()
-        with:
-          report_paths: '**/build/test-results/*/TEST-*.xml'
-          check_name: PEEPS test report
-
-  acceptance-tests:
-    name: Acceptance tests (${{ matrix.tag }})
-    needs:
-      - docker-build
-    if: success()
-    strategy:
-      fail-fast: false
-      matrix:
-        # list of tag expression being executed in parallel
-        # for PR, only selective tests are run.
-        # More comprehensive suites are scheduled to run in master
-        tag:
-          - 'basic || basic-raft || (advanced && raft) || networks/typical::raft'
-          - 'basic || basic-istanbul || (advanced && istanbul && !block-heights) || networks/typical::istanbul'
-          - 'basic || basic-istanbul || (advanced && istanbul && !block-heights) || empty-block-period || block-reward || networks/typical::qbft'
-          - 'validator-management && networks/template::istanbul-3plus1'
-          - 'validator-management && networks/template::qbft-3plus1'
-          - 'multitenancy && networks/plugins::raft-multitenancy'
-          - 'migration && networks/template::istanbul-4nodes'
-          - 'migration && networks/template::raft-4nodes'
-          - 'basic || networks/typical::raftmps'
-          - 'basic || networks/typical::istanbulmps'
-          - 'basic || networks/typical::qbftmps'
-    runs-on: ubuntu-20.04
-    steps:
-      - name: 'Download workflow artifact - Docker image'
-        uses: actions/download-artifact@v1
-        with:
-          name: docker-image
-      - name: 'Load Docker image'
-        id: setup
-        run: |
-          tar xfvz docker-image/quorum-pr.tar.gz
-          docker load --input quorum-pr.tar
-          docker_env_file="${{ runner.temp }}/env.list"
-          echo "TF_VAR_quorum_docker_image={ name = \"quorumengineering/quorum:pr\", local = true }" >> $docker_env_file
-          echo "::set-output name=outputDir::${{ runner.temp }}"
-          echo "::set-output name=dockerEnvFile::$docker_env_file"
-      - name: 'Run acceptance tests'
-        run: |
-          cat ${{ steps.setup.outputs.dockerEnvFile }}
-          docker run --rm \
-            --network host \
-            -v /var/run/docker.sock:/var/run/docker.sock \
-            -v ${{ steps.setup.outputs.outputDir }}:${{ steps.setup.outputs.outputDir  }} \
-            --env-file ${{ steps.setup.outputs.dockerEnvFile }} \
-            quorumengineering/acctests:latest test \
-              -Pauto \
-              -Dauto.outputDir=${{ steps.setup.outputs.outputDir  }} \
-              -Dtags="${{ matrix.tag }}"
-      - name: 'Debug'
-        run: |
-          docker images
-          docker ps -a
+#  peeps-tests:
+#    name: Run PEEPS tests
+#    needs:
+#      - docker-build
+#    runs-on: ubuntu-20.04
+#    steps:
+#      - name: 'Checkout'
+#        uses: actions/checkout@v2
+#      - name: 'Download workflow artifact - Docker image'
+#        uses: actions/download-artifact@v1
+#        with:
+#          name: docker-image
+#      - name: 'Load Docker image'
+#        id: setup
+#        run: |
+#          tar xfvz docker-image/quorum-pr.tar.gz
+#          docker load --input quorum-pr.tar
+#          docker image tag quorumengineering/quorum:pr quorumengineering/quorum:develop
+#          docker image ls
+#      - name: Set up Java
+#        uses: actions/setup-java@v2
+#        with:
+#          distribution: 'adopt'
+#          java-version: 11
+#          check-latest: true
+#      - name: PEEPS
+#        run: |
+#          cd build
+#          ./run-peeps.sh
+#      - name: PEEPS Test Report
+#        uses: mikepenz/action-junit-report@v2
+#        if: always()
+#        with:
+#          report_paths: '**/build/test-results/*/TEST-*.xml'
+#          check_name: PEEPS test report
+#
+#  acceptance-tests:
+#    name: Acceptance tests (${{ matrix.tag }})
+#    needs:
+#      - docker-build
+#    if: success()
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        # list of tag expression being executed in parallel
+#        # for PR, only selective tests are run.
+#        # More comprehensive suites are scheduled to run in master
+#        tag:
+#          - 'basic || basic-raft || (advanced && raft) || networks/typical::raft'
+#          - 'basic || basic-istanbul || (advanced && istanbul && !block-heights) || networks/typical::istanbul'
+#          - 'basic || basic-istanbul || (advanced && istanbul && !block-heights) || empty-block-period || block-reward || networks/typical::qbft'
+#          - 'validator-management && networks/template::istanbul-3plus1'
+#          - 'validator-management && networks/template::qbft-3plus1'
+#          - 'multitenancy && networks/plugins::raft-multitenancy'
+#          - 'migration && networks/template::istanbul-4nodes'
+#          - 'migration && networks/template::raft-4nodes'
+#          - 'basic || networks/typical::raftmps'
+#          - 'basic || networks/typical::istanbulmps'
+#          - 'basic || networks/typical::qbftmps'
+#    runs-on: ubuntu-20.04
+#    steps:
+#      - name: 'Download workflow artifact - Docker image'
+#        uses: actions/download-artifact@v1
+#        with:
+#          name: docker-image
+#      - name: 'Load Docker image'
+#        id: setup
+#        run: |
+#          tar xfvz docker-image/quorum-pr.tar.gz
+#          docker load --input quorum-pr.tar
+#          docker_env_file="${{ runner.temp }}/env.list"
+#          echo "TF_VAR_quorum_docker_image={ name = \"quorumengineering/quorum:pr\", local = true }" >> $docker_env_file
+#          echo "::set-output name=outputDir::${{ runner.temp }}"
+#          echo "::set-output name=dockerEnvFile::$docker_env_file"
+#      - name: 'Run acceptance tests'
+#        run: |
+#          cat ${{ steps.setup.outputs.dockerEnvFile }}
+#          docker run --rm \
+#            --network host \
+#            -v /var/run/docker.sock:/var/run/docker.sock \
+#            -v ${{ steps.setup.outputs.outputDir }}:${{ steps.setup.outputs.outputDir  }} \
+#            --env-file ${{ steps.setup.outputs.dockerEnvFile }} \
+#            quorumengineering/acctests:latest test \
+#              -Pauto \
+#              -Dauto.outputDir=${{ steps.setup.outputs.outputDir  }} \
+#              -Dtags="${{ matrix.tag }}"
+#      - name: 'Debug'
+#        run: |
+#          docker images
+#          docker ps -a
